"""empty message

Revision ID: 2dc47abb2749
Revises: 536806105cee
Create Date: 2022-05-31 11:48:55.437728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc47abb2749'
down_revision = '536806105cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'customer',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shipment', 'supplier',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'supplier',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shipment', 'customer',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
