"""empty message

Revision ID: 61499804ecf9
Revises: 2dc47abb2749
Create Date: 2022-05-31 11:50:39.087261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61499804ecf9'
down_revision = '2dc47abb2749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('customerid', sa.Integer(), nullable=True))
    op.add_column('shipment', sa.Column('supplierid', sa.Integer(), nullable=True))
    op.drop_constraint('shipment_supplier_fkey', 'shipment', type_='foreignkey')
    op.drop_constraint('shipment_customer_fkey', 'shipment', type_='foreignkey')
    op.create_foreign_key(None, 'shipment', 'user', ['supplierid'], ['id'])
    op.create_foreign_key(None, 'shipment', 'user', ['customerid'], ['id'])
    op.drop_column('shipment', 'customer')
    op.drop_column('shipment', 'supplier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('supplier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('shipment', sa.Column('customer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.create_foreign_key('shipment_customer_fkey', 'shipment', 'user', ['customer'], ['id'])
    op.create_foreign_key('shipment_supplier_fkey', 'shipment', 'user', ['supplier'], ['id'])
    op.drop_column('shipment', 'supplierid')
    op.drop_column('shipment', 'customerid')
    # ### end Alembic commands ###
